# -*- coding: utf-8 -*-
"""Car Market Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSqkoXQa8y5h2hx-br2hMSs6smulB2vd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/1776311302-P3-Car Market Trends Analysis with Car Dekho Data (1).csv')

df.head()

df.shape

df.columns.to_list()

df.describe(include='all').T

from os import dup
duplicate_count = df.duplicated().sum()
print('Duplcate Rows', duplicate_count)

df = df.drop_duplicates().copy()
print('Duplicate remaining',df.duplicated().sum)

print(df.isnull().sum())

print("Number of duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

current_year = 2026

df["Car_Age"] = current_year - df["Year"]

df[["Car_Name", "Year", "Car_Age"]].head()

expensive_cars = df.sort_values(
    by="Selling_Price",
    ascending=False
)

expensive_cars[["Car_Name", "Selling_Price", "Present_Price"]].head(10)

fuel_price = df.groupby("Fuel_Type")["Selling_Price"].mean()

print(fuel_price)

fuel_price.plot(kind="bar")

plt.title("Average Selling Price by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Average Selling Price")
plt.xticks(rotation=0)
plt.show()

transmission_price = df.groupby("Transmission")["Selling_Price"].mean()

print(transmission_price)

transmission_price.plot(kind="bar")

plt.title("Average Selling Price by Transmission")
plt.xlabel("Transmission")
plt.ylabel("Average Selling Price")
plt.xticks(rotation=0)
plt.show()

plt.scatter(df["Present_Price"], df["Selling_Price"])

plt.title("Present Price vs Selling Price")
plt.xlabel("Present Price")
plt.ylabel("Selling Price")
plt.show()

plt.scatter(df["Kms_Driven"], df["Selling_Price"])

plt.title("Selling Price vs Kilometers Driven")
plt.xlabel("Kilometers Driven")
plt.ylabel("Selling Price")
plt.show()

fuel_count = df["Fuel_Type"].value_counts()

print(fuel_count)

seller_count= df['Seller_Type'].value_counts()
seller_count.plot(kind="bar")

plt.title("Number of Cars by Seller Type")
plt.xlabel("Seller Type")
plt.ylabel("Number of Cars")
plt.xticks(rotation=0)
plt.show()

transmission_count = df["Transmission"].value_counts()

print(transmission_count)

transmission_count.plot(kind="bar")

plt.title("Manual vs Automatic Cars")
plt.xlabel("Transmission")
plt.ylabel("Number of Cars")
plt.xticks(rotation=0)
plt.show()

numeric_columns = [
    "Year",
    "Selling_Price",
    "Present_Price",
    "Kms_Driven",
    "Owner",
    "Car_Age"
]

correlation = df[numeric_columns].corr()

print(correlation)

plt.figure(figsize=(8, 6))

plt.imshow(correlation, cmap="coolwarm", interpolation="nearest")

plt.colorbar()

plt.xticks(
    range(len(correlation.columns)),
    correlation.columns,
    rotation=45
)

plt.yticks(
    range(len(correlation.columns)),
    correlation.columns
)

plt.title("Correlation Heatmap")

plt.show()

top_cars = df["Car_Name"].value_counts().head(10)

print(top_cars)

top_cars.plot(kind="bar")

plt.title("Top 10 Most Frequently Listed Cars")
plt.xlabel("Car Name")
plt.ylabel("Number of Listings")
plt.xticks(rotation=45)
plt.show()

age_price = df.groupby("Car_Age")["Selling_Price"].mean()

print(age_price)

plt.plot(age_price.index, age_price.values, marker="o")

plt.title("Car Age vs Average Selling Price")
plt.xlabel("Car Age")
plt.ylabel("Average Selling Price")
plt.grid(True)

plt.show()

print("Total number of cars:", len(df))

print("Average selling price:",
      round(df["Selling_Price"].mean(), 2))

print("Average present price:",
      round(df["Present_Price"].mean(), 2))

print("Most common fuel type:",
      df["Fuel_Type"].mode()[0])

print("Most common transmission:",
      df["Transmission"].mode()[0])

print("Most common seller type:",
      df["Seller_Type"].mode()[0])

print("Most listed car:",
      df["Car_Name"].mode()[0])